name: Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact-name: BP-Order-Management-Linux
          - os: windows-latest
            artifact-name: BP-Order-Management-Windows
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Tkinter (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install dependencies
        run: uv sync

      - name: Build executable
        run: uv run pyinstaller --noconfirm BP-Order-Management.spec

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/BP-Order-Management*
